## Exercise 1: NumPy: Create an array with values ranging from 12 to 38

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


### Solution 1:

In [2]:
import numpy as np

In [3]:
arr = np.arange(12, 39)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### Solution 2:

In [5]:
arr1 = np.ones((3,4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr1_pad = np.pad(arr1, (1), mode='constant', constant_values=(0))
arr1_pad

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Exercise 3: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


### Solution 3

In [12]:
array1 = [1,2,3,4,5,6,7,8]
print(type(array1))

<class 'list'>


In [13]:
list2arr = np.asarray(array1)
list2arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
tuple1 = ([8,4,6],[1,2,3])
print(type(tuple1))

<class 'tuple'>


In [18]:
tuple2arr = np.asarray(tuple1)
tuple2arr


array([[8, 4, 6],
       [1, 2, 3]])

In [20]:
tuple2arr.shape

(2, 3)

## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


### Solution 4:

In [21]:
f = np.array([ 0., 12. ,  45.21 ,34.  , 99.91])

In [26]:
c_temp = f -32
c_temp

array([-32.  , -20.  ,  13.21,   2.  ,  67.91])

In [27]:
c = c_temp * 5/9
c

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


### Solution 5

In [32]:
arra = np.array([1,2,3])

print("size of array: ", arra.size)
print("Length of one array element in bytes: ", arra.itemsize)
print("Total bytes consumed by the elements of the array: ", arra.size*arra.itemsize)

size of array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


8

## Exercise 6: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [33]:
n1 = np.array([10, 10, 20, 20, 30, 30])

In [35]:
n1_unique = np.unique(n1)
n1_unique

array([10, 20, 30])

In [39]:
n2 = [[1,1],[2,3]]
n2

[[1, 1], [2, 3]]

In [38]:
n2_unique = np.unique(n2)
n2_unique

array([1, 2, 3])

## Exercise 7: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Solution 7:

In [40]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


### Solution 8:


In [43]:
spacedArray = np.linspace(2.5,6.5,30)

In [44]:
spacedArray

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

## Exercise 9: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


### Solution 9

In [46]:
array1 = np.array([10,20,30])
array2 = np.array([40,50,60])

In [49]:
array3 = np.stack((array1, array2), axis=0)
array3

array([[10, 20, 30],
       [40, 50, 60]])

In [50]:
array4 = np.stack((array1,array2), axis=1)
array4

array([[10, 40],
       [20, 50],
       [30, 60]])

## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [11]:
a1 = np.zeros((5,5))
a1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
for i in range(0,a1)

In [5]:
rows = np.arange(0,5)
rows

array([0, 1, 2, 3, 4])

In [6]:
np.stack((rows,rows,rows,rows), axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Exercise 11: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Solution 11:

In [20]:
tempArr = np.arange(1,100)
tempArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
newArray = tempArr[((tempArr % 3 == 0) | (tempArr % 5 ==0)) ]
newArray

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36,
       39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72,
       75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99])

In [24]:
print("result: ",np.sum(newArray))

result:  2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [29]:
x = np.arange(4)
y = np.arange(4)

for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Solution 12:

In [22]:
x11 = np.arange(4)
y11 = np.arange(8).reshape(2,4)


In [23]:
y11

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
itr = np.nditer(([x11,y11]),flags=['f_index'])
for a,b in itr:
    print("{} : {} ".format(a, itr.index))
    

0 : 0 
1 : 2 
2 : 4 
3 : 6 
0 : 1 
1 : 3 
2 : 5 
3 : 7 


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [13]:
import numpy as np
inputArray = np.array([[0.42436315, 0.48558583, 0.32924763],[0.7439979,  0.58220701, 0.38213418],
                       [0.5097581,  0.34528799, 0.1563123 ]])
inputArray

array([[0.42436315, 0.48558583, 0.32924763],
       [0.7439979 , 0.58220701, 0.38213418],
       [0.5097581 , 0.34528799, 0.1563123 ]])

In [14]:
rows = inputArray.shape[0]
columns = inputArray.shape[1]
outputArray = inputArray.copy()
for i in range(0,rows):
    for j in range(0,columns):
        if (outputArray[i][j] > .5):
            outputArray[i][j] = .5
outputArray
            
        

array([[0.42436315, 0.48558583, 0.32924763],
       [0.5       , 0.5       , 0.38213418],
       [0.5       , 0.34528799, 0.1563123 ]])

## Exercise 14: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


### Solution 14:

In [39]:
emptyarr = np.array([])
emptyarr

array([], dtype=float64)

In [40]:
emptyarr = np.append(emptyarr, np.array([10,20,30]), axis=0)
emptyarr = np.append(emptyarr, np.array([40,50,60]), axis=0)
emptyarr.reshape(2,3)

array([[10., 20., 30.],
       [40., 50., 60.]])

## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [62]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])
arr1

array([1, 2, 3])

In [63]:
arr3 = np.stack((arr1,arr2), axis=0)
arr3

array([[1, 2, 3],
       [2, 3, 4]])

In [65]:
arr1new = np.array([1,2,3]).reshape(3,1)
arr2new = np.array([2,3,4]).reshape(3,1)
arr1new

array([[1],
       [2],
       [3]])

In [66]:
arr3new = np.vstack((arr1new,arr2new))

In [67]:
arr3new

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])